version: '3'
services: 
  db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports: 
      - '4306:3306'
    volumes: 
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes: 
      - .:/Sharing_Portfolio
    ports: 
      - '3000:3000'
    depends_on: 
      - db
    stdin_open: true
    tty: true
volumes: 
  mysql-data: