default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  

development:
  <<: *default
  database: Sharing_Portfolio_development
  username: root
  password: password
  host: db


test:
  <<: *default
  database: Sharing_Portfolio_test
  username: root
  password: password
  host: db


production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
