default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  

development:
  <<: *default
  database: Sharing_Portfolio_development
  username: root
  password: password
  host: db


test:
  <<: *default
  database: Sharing_Portfolio_test
  username: root
  password: password
  host: db


production:
  <<: *default
  database: Sharing_Portfolio_production
  username: root
  password: Kk-10310723
  socket: /var/lib/mysql/mysql.sock
